### ISSUE TITLE
Test Swift

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/asm.js-language-support#1]

**Comment by MggMuggins** [comment]
This might provide some insight: https://stackoverflow.com/questions/46572144/compile-swift-to-webassembly

**Comment by ChristianMurphy** [comment]
Thanks @MggMuggins!

That holds consistent with the [results collected from Swift 2 back in the first round of testing](https://github.com/ChristianMurphy/compile-to-web/tree/v1.0.0).

The main challange is that [WASM and LLVM IR are different languages](https://github.com/WebAssembly/design/blob/master/FAQ.md#why-not-just-use-llvm-bitcode-as-a-binary-format), [Emscripten](https://github.com/kripken/emscripten) can compile many, if not most, [LLVM IR operations](https://llvm.org/docs/LangRef.html#abstract) into WASM but [not all operations](https://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html).

WASM limitations the [Emscripten can't cover over](https://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html) are what is currently preventing Swift from compiling to WASM. What remains to be seen is if the right combination of Swift compiler flags can overcome the issues or if it will require changes to Swift's compiler.

**Comment by ChristianMurphy** [comment]
Swift has been tested, it is currently not supported, more details in the swift readme file.
