### ISSUE TITLE
Add Kotlin Native

### ISSUE THREAD

**Issue by NathanFlurry** [ChristianMurphy/asm.js-language-support#15]
Kotlin Native recently [added support for WASM](https://blog.jetbrains.com/kotlin/2017/11/kotlinnative-v0-4-released-objective-c-interop-webassembly-and-more/). Probably a good idea to add this, maybe I'll take a shot at it if I get a chance.

**Comment by ChristianMurphy** [comment]
Added in https://github.com/ChristianMurphy/compile-to-web/commit/b9404016ec91be2f8bb744374bc2ddc72ec85a31
