### ISSUE TITLE
Add plz Typescript

### ISSUE THREAD

**Issue by MaxGraey** [ChristianMurphy/asm.js-language-support#18]
Compilers:

- [AssemblyScript](https://github.com/AssemblyScript/assemblyscript)
- [TurboScript](https://github.com/01alchemist/TurboScript) (Not maintained anymore)
- [Speedy.js](https://github.com/MichaReiser/speedy.js)

**Comment by ChristianMurphy** [comment]
Thanks @MaxGraey!
Would you be interested in opening a pull request to add TypeScript?

**Comment by ChristianMurphy** [comment]
TypeScript has been added to the list, it is currently not checked because assemble script and turboscript both have typescript like syntax, do not support most of typescript.

**Comment by MaxGraey** [comment]
TurboScript and Speedy.js not maintaned anymore. I will add AssemblyScript PR later. Thanks!
