### ISSUE TITLE
Scala?

### ISSUE THREAD

**Issue by findingorder** [ChristianMurphy/asm.js-language-support#20]
Please add Scala to your list.

**Comment by ChristianMurphy** [comment]
Sounds good!
@DeliciousPickle would you be interested in opening a PR to add Scala?

**Comment by ChristianMurphy** [comment]
https://github.com/scala-js/scala-js/issues/1747

**Comment by ChristianMurphy** [comment]
Hey @DeliciousPickle Scala has been added to the list.
Scala native supports compiling to llvm, but I am not seeing a WASM target yet.
I'm going to close this ticket, feel free to add an update if/when a WASM target becomes available.

**Comment by nafg** [comment]
Some pointers related to running scala on WASM:

1. https://github.com/shadaj/scala-native-wasm -- seems to use scala-native to get LLVM code, then emscripten to compile that to WASM.
2. http://teavm.org/
 > TeaVM is an ahead-of-time compiler for Java bytecode that emits JavaScript and WebAssembly that runs in a browser. Its close relative is the well-known GWT. The main difference is that TeaVM does not require source code, only compiled class files. Moreover, the source code is not required to be Java, so TeaVM successfully compiles Kotlin and Scala.
