### ISSUE TITLE
swift updates - watch this space

### ISSUE THREAD

**Issue by johndpope** [ChristianMurphy/asm.js-language-support#26]
https://github.com/kripken/emscripten/issues/2427

to quote @maxdesiatov
"LLVM 7.0 was released yesterday with a lot of progress for WebAssembly target support. While the backend is still marked as experimental, not as much patching of upstream LLVM repositories should be needed. I've pulled 7.0 updates into Apple swift's fork repositories and rebased the changes in the main swift repository by @patcheng, while also fixing a few compilation issues.

Now the whole fresh toolchain with patches from above comments compiles for me, although I haven't checked yet if the actual WebAssembly support has improved. Going to look into that soon. I'm doing the work in these forks and branches:"

https://github.com/maxdesiatov/swift/tree/swift-to-wasm
https://github.com/maxdesiatov/swift-compiler-rt/tree/wasm
https://github.com/maxdesiatov/swift-llvm/tree/wasm
https://github.com/maxdesiatov/swift-clang/tree/wasm

**Comment by ChristianMurphy** [comment]
Official Swift PR https://github.com/apple/swift/pull/20684

**Comment by orestesgaolin** [comment]
Here is a sample website discussing the possibilities: https://swiftwasm.org

**Comment by johndpope** [comment]
Please open a PR to update this repo with relevant swift stuff  - https://github.com/ChristianMurphy/compile-to-web/tree/master/Swift

I'm doing a spring clean on older issues and closing this.
