### ISSUE TITLE
Try Nim

### ISSUE THREAD

**Issue by Wulfklaue** [ChristianMurphy/asm.js-language-support#7]
Nim compiles down to C code. So it in theory can compile to webasm. 

Note: The GC can be a issue.

**Comment by ChristianMurphy** [comment]
related to nim-lang/Nim/issues/2960

**Comment by ChristianMurphy** [comment]
Hey @Wulfklaue! :wave: 
Would you be interested in opening a pull request testing Nim to WASM support?

**Comment by ChristianMurphy** [comment]
It looks like there is now official support in Nim lang https://forum.nim-lang.org/t/2838

**Comment by ChristianMurphy** [comment]
Support appears to be working, documented in https://github.com/ChristianMurphy/compile-to-web/commit/8b14243fe67976981c1a673c80a0c5c89bed4949
